# bash_profile
#
# Symlinked to the vagrant user's home directory. This loads
# the default .bashrc provided by the virtual machine, which in
# turn loads the .bash_aliases file that we provide. Use this
# bash_profile to set environment variables and such.

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# setup bash prompt
if [ -n "$BASH_VERSION" ]; then
    # include .bash_prompt if it exists
    if [ -f "$HOME/.bash_prompt" ]; then
        . "$HOME/.bash_prompt"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Set the WP_TESTS_DIR path directory so that we can use phpunit inside
# plugins almost immediately.
export WP_TESTS_DIR=/srv/www/wordpress-develop/tests/phpunit/

# add autocomplete for grunt
eval "$(grunt --completion=bash)"

# add autocomplete for wp-cli
. /srv/www/wp-cli/utils/wp-completion.bash

# PHPCS path
export PATH="$PATH:/srv/www/phpcs/scripts/"

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion
